from django.conf.urls.defaults import *
from django.conf import settings

urlpatterns = patterns('',
	(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT }),
	(r'^$','plan.views.index'),
	(r'^department/$','plan.views.form_department'),
	(r'^department/(?P<id>\d+)$','plan.views.department'),
	(r'^attribute/$','plan.views.form_attribute'),
	(r'^attribute/(?P<id>\d+)$','plan.views.attribute'),
	(r'^degree/$','plan.views.form_degree'),
	(r'^degree/(?P<id>\d+)$','plan.views.degree'),
	(r'^course/$','plan.views.form_course'),
	(r'^course/(?P<id>\d+)$','plan.views.course'),
	(r'^period_day/$','plan.views.form_period_day'),
	(r'^period_day/(?P<id>\d+)$','plan.views.period_day'),
	(r'^period/$','plan.views.form_period'),
	(r'^period/(?P<id>\d+)$','plan.views.period'),
	(r'^offering/$','plan.views.form_offering'),
	(r'^offering/(?P<id>\d+)$','plan.views.offering'),
	(r'^student/$','plan.views.form_student'),
	(r'^student/(?P<id>\d+)$','plan.views.student'),
	(r'^asp/$','plan.views.asp'),
	(r'^write_asp/(?P<s>\d+)/(?P<min>\d+)/(?P<max>\d+)/$','plan.views.write_asp'),
	(r'^status/$', 'plan.views.status'),
	(r'^view_status/$', 'plan.views.view_status'),
	(r'^results/$', 'plan.views.results'),
	(r'^results/(?P<s>\d+)/(?P<p>\d+)$', 'plan.views.results_paged'),
	(r'^schedules/(?P<s>\d+)/(?P<p>\d+)/$', 'plan.views.schedule'),
	(r'^plan/$', 'plan.views.plan'),
	(r'^calendar/(?P<s>\d+)$', 'plan.views.calendar'),
	(r'^num_schedules/$', 'plan.views.num_schedules'),
)